In [1]:
import numpy as np

In [8]:
# Dinámica de una caída libre

g =  - 9.8 # m/s
y0 = 10 # m

t = np.sqrt(-2*y0/g)
v = g * t

print(f"""
Altura de caída: {y0} m
Tiempo de caída: {t} s
Velocidad en impacto: {v} m/s
Velocidad en impacto: {v * 3600/1000} km/h
""")


Altura de caída: 10 m
Tiempo de caída: 1.4285714285714286 s
Velocidad en impacto: -14.000000000000002 m/s
Velocidad en impacto: -50.400000000000006 km/h



In [19]:
# masa (kg)
m = 60e-6 # Hormiga
m = 65e-3 #  
m = 65 # Humano

# cantidad de movimiento
# inicial
v_i = v
p_i = m * v_i


# final
v_f = 0
p_f = m * v_f

# Duración impacto
t = .1

# Fuerza
F = (p_f - p_i)/t


print(f"""
momento inicial: {p_i} kg m/s
momento final: {p_f} kg m/s
duración impacto: {t} s
Fuerza: {F} N
""")




momento inicial: -910.0000000000001 kg m/s
momento final: 0 kg m/s
duración impacto: 0.1 s
Fuerza: 9100.0 N



In [28]:
a = np.random.rand(5,5)-0.5
print(a)
np.where(a>=0, a, a)

[[-0.09556658  0.21522412 -0.09936161  0.45830763  0.43551074]
 [ 0.2769654   0.45265193  0.43889261  0.46526239 -0.36324448]
 [-0.09390833  0.37778979 -0.07815668  0.31783286 -0.01910572]
 [-0.47801263  0.24999664 -0.3005847   0.24509474  0.43384713]
 [ 0.12876365  0.20218214 -0.37067458  0.47485586  0.24327057]]


array([[-0.09556658,  0.21522412, -0.09936161,  0.45830763,  0.43551074],
       [ 0.2769654 ,  0.45265193,  0.43889261,  0.46526239, -0.36324448],
       [-0.09390833,  0.37778979, -0.07815668,  0.31783286, -0.01910572],
       [-0.47801263,  0.24999664, -0.3005847 ,  0.24509474,  0.43384713],
       [ 0.12876365,  0.20218214, -0.37067458,  0.47485586,  0.24327057]])